locals {
  credentials_secret_name = "dir-credentials"
  api_fqdn                = "api.${var.base_fqdn}"
  zot_fqdn                = "zot.${var.base_fqdn}"
  routing_fqdn            = "routing.${var.base_fqdn}"
}

# --- Credentials generated by terraform ---
resource "random_password" "postgres" {
  length  = 32
  special = false
}

resource "random_password" "zot_admin" {
  length  = 24
  special = false
}

resource "htpasswd_password" "zot" {
  password = random_password.zot_admin.result
}

resource "kubernetes_secret" "dir_credentials" {
  metadata {
    name      = local.credentials_secret_name
    namespace = var.namespace
  }

  type = "Opaque"

  data = {
    "postgres-password" = random_password.postgres.result
    "password"         = random_password.postgres.result
    "zot-htpasswd"     = "admin:${htpasswd_password.zot.bcrypt}"
  }

  depends_on = [kubectl_manifest.namespace]
}

# Create the namespace ourselves so the Secret can land before the chart needs it.
# helm_release.dir has create_namespace = false because we own it here.
resource "kubectl_manifest" "namespace" {
  yaml_body = yamlencode({
    apiVersion = "v1"
    kind       = "Namespace"
    metadata = {
      name = var.namespace
    }
  })
}

# --- dir umbrella chart ---
locals {
  # Default authz policies that allow local trust domain full access and federated peers limited access
  default_authz_policies = <<-EOF
    p,${var.trust_domain},*
    p,*,/agntcy.dir.store.v1.StoreService/Pull
    p,*,/agntcy.dir.store.v1.StoreService/PullReferrer
    p,*,/agntcy.dir.store.v1.StoreService/Lookup
    p,*,/agntcy.dir.store.v1.SyncService/RequestRegistryCredentials
  EOF

  # Use custom policies if provided, otherwise use defaults
  authz_policies = var.authz_policies_csv != "" ? var.authz_policies_csv : local.default_authz_policies

  # Construct the complete authz_policies_csv YAML block with proper formatting
  authz_policies_yaml = "    ${replace(local.authz_policies, "\n", "\n    ")}"

  # Manually construct federation YAML with proper indentation
  federation_yaml = length(var.federation_peers) > 0 ? join("\n", flatten([
    for peer in var.federation_peers : [
      "      - className: ${peer.className}",
      "        trustDomain: ${peer.trustDomain}",
      "        bundleEndpointURL: ${peer.bundleEndpointURL}",
      "        bundleEndpointProfile:",
      "          type: ${peer.bundleEndpointProfile.type}"
    ]
  ])) : ""

  # Default routing bootstrap peers if none provided
  default_routing_bootstrap_peers = [
    "/dns4/routing.ads.outshift.io/tcp/5555/p2p/12D3KooWLf9p3cedc86xGQBaqak6rAFmQk1HxKAK1yh7umHE3amu"
  ]

  routing_bootstrap_peers = length(var.routing_bootstrap_peers) > 0 ? var.routing_bootstrap_peers : local.default_routing_bootstrap_peers

  # Manually construct autosync YAML with proper indentation
  autosync_yaml = var.routing_autosync_enabled ? join("\n", flatten([
    ["      enabled: true"],
    ["      peerlist:"],
    [for peer in var.routing_autosync_peerlist : "        - ${peer}"]
  ])) : "      enabled: false"

  dir_values = templatefile("${path.module}/values/dir.yaml.tftpl", {
    apiserver_image_tag         = var.dir_chart_version
    trust_domain                = var.trust_domain
    base_fqdn                   = var.base_fqdn
    namespace                   = var.namespace
    credentials_secret_name     = local.credentials_secret_name
    zot_pvc_size                = var.zot_pvc_size
    federation_yaml             = local.federation_yaml
    authz_policies_csv          = local.authz_policies_yaml
    routing_bootstrap_peers     = local.routing_bootstrap_peers
    routing_autosync_yaml       = local.autosync_yaml
    reconciler_enabled          = var.reconciler_enabled
    reconciler_image_tag        = var.reconciler_image_tag
    reconciler_regsync_enabled  = var.reconciler_regsync_enabled
    reconciler_regsync_interval = var.reconciler_regsync_interval
    reconciler_regsync_timeout  = var.reconciler_regsync_timeout
    reconciler_indexer_enabled  = var.reconciler_indexer_enabled
    reconciler_indexer_interval = var.reconciler_indexer_interval
  })
}

resource "helm_release" "dir" {
  name             = "dir"
  namespace        = var.namespace
  create_namespace = false # we own the namespace via kubectl_manifest

  repository = "oci://ghcr.io/agntcy/dir/helm-charts"
  chart      = "dir"
  version    = var.dir_chart_version

  values = [local.dir_values]

  timeout          = 900
  wait             = true
  wait_for_jobs    = false
  cleanup_on_fail  = true
  disable_webhooks = true

  depends_on = [
    kubectl_manifest.namespace,
    kubernetes_secret.dir_credentials,
  ]
}
